### ISSUE TITLE
ant-design-vue的权重问题

### ISSUE THREAD

**Issue by tangchi695** [GitOfZGT/some-loader-utils#1]
你好，我在antd-vue的项目里使用这个插件，大部分样式都可以切换，但是遇到一个问题，编译的结果会影响按钮这类组件样式的权重。
![image](https://user-images.githubusercontent.com/16055749/117916559-fcb1d800-b319-11eb-9670-1a676ecf90e3.png)
像这个地方本来这个按钮是primary类型的，但是增加的theme-black这个类只影响到了默认的ant-btn类，导致primary类型的样式都失效了。
我试过自己重新定义primary颜色之类的方法都没有生效。
想请教一下作者这种问题应该如何解决呢？

**Comment by tangchi695** [comment]
大概弄清除怎么解决了，给两套样式的primary-color设置成不一样的颜色值就行了。

**Comment by GitOfZGT** [comment]
在v1.2.0中，multipleScopeVars只有一项时，只做变量提升，不会添加对应scopeName的className

**Comment by GitOfZGT** [comment]
可能会不可避免的出现以下样式权重问题（在element-ui v2.x 有发现），在 @zougt/some-loader-utils v1.3.0 添加了 multipleScopeVars[].includeStyles 用于处理此类问题。
![image](https://user-images.githubusercontent.com/21262000/133917696-804f8a75-2540-48e4-8b46-84ddc0b3fef1.png)
处理之后可以是这样的
![image](https://user-images.githubusercontent.com/21262000/133917724-4d64f4e5-af9b-4dd6-8481-b10b20f3204f.png)
multipleScopeVars[].includeStyles 的使用参考文档
