### ISSUE TITLE
按照readme和demo里的配置移植到我的项目里，切换主题不生效

### ISSUE THREAD

**Issue by mulianju** [GitOfZGT/some-loader-utils#14]

**Comment by mulianju** [comment]
我的项目采用的是动态主题颜色模式，按照readme和demo里的配置移植过来，调整了三天了，一直不生效，求大神指点

**Comment by dxh-vip** [comment]
[getThemeColorLess.zip](https://github.com/GitOfZGT/some-loader-utils/files/8896082/getThemeColorLess.zip)

**Comment by dxh-vip** [comment]
这是demo

**Comment by GitOfZGT** [comment]
![image](https://user-images.githubusercontent.com/21262000/173495592-dcc625cf-4ee4-4210-9335-263820aae219.png)
![image](https://user-images.githubusercontent.com/21262000/173495801-3feda0f7-0471-45e3-a81d-6f1bda8743f3.png)

**Comment by mulianju** [comment]
> ![image](https://user-images.githubusercontent.com/21262000/173495592-dcc625cf-4ee4-4210-9335-263820aae219.png) ![image](https://user-images.githubusercontent.com/21262000/173495801-3feda0f7-0471-45e3-a81d-6f1bda8743f3.png)

感谢大神，果然可以了
