### ISSUE TITLE
如何替换多个颜色，比如我们自己定义了一套梯度色计算规则，这种能实现吗

### ISSUE THREAD

**Issue by mulianju** [GitOfZGT/some-loader-utils#15]

**Comment by GitOfZGT** [comment]
梯度色规则如果用的less/sass的颜色函数，向主色中混入百分比的#000或者#fff，是可以的。要使用多个颜色替换相对应的梯度可以用这个属性
![image](https://user-images.githubusercontent.com/21262000/173732358-f2f4a599-a572-4d4e-ac11-517cf96ff7ed.png)

**Comment by mulianju** [comment]
> 色中混入百分比的#000或者#fff

gradientReplacer里该怎么配置呢，json结构是`{'原色':'目标色'...}`这样的结构吗，原色值是怎么获取来的呢

**Comment by GitOfZGT** [comment]
> > 色中混入百分比的#000或者#fff
> 
> gradientReplacer里该怎么配置呢，json结构是`{'原色':'目标色'...}`这样的结构吗，原色值是怎么获取来的呢

原色值是给插件的那个 theme-vars.less文件中的来的

**Comment by GitOfZGT** [comment]
> > > 色中混入百分比的#000或者#fff
> > 
> > 
> > gradientReplacer里该怎么配置呢，json结构是`{'原色':'目标色'...}`这样的结构吗，原色值是怎么获取来的呢
> 
> 原色值是给插件的那个 theme-vars.less文件中的来的

```less
@primary-color:#8F76C5;  // 依赖它形成的梯度色会改变
@my-second-color:#D58251; //  另外一个主色，依赖它形成的梯度色也会改变
```

gradientReplacer就会有 {"#8F76C5":"目标值","#D58251":"目标值"}

**Comment by mulianju** [comment]
已经搞定了，感谢大神
