### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by ZeroOneJs** [GitOfZGT/some-loader-utils#2]
编译时有两种情况会报如下图错误
<img width="816" alt="WX20210816-164419@2x" src="https://user-images.githubusercontent.com/80911956/129536916-39d813ff-3ada-4712-b5a6-ca4a39d75c9a.png">

## 情况一：
less文件中出现多行嵌套注释时，如下图：
<img width="188" alt="WX20210816-164352@2x" src="https://user-images.githubusercontent.com/80911956/129537202-9f8bd845-5d29-4a00-958c-c23f5de6eaa3.png">

## 情况二：
less文件中引入css文件
```less
@import "./font/iconfont.css";
```

最后插件做的很棒，感谢作者提供

**Comment by GitOfZGT** [comment]
1. 情况一在 v1.2.0 已修复
2. 情况二是sass或less本身不支持直接 @import css文件，这里不会处理
