### ISSUE TITLE
配置跟版本问题

### ISSUE THREAD

**Issue by geekpeng** [GitOfZGT/some-loader-utils#3]
这个工具非常好刚特别满足我现在的需要,

但是在使用的时候遇到了一些问题

我在  vue.config.js 里面的配置:

`
const path = require("path");
const { getLess } = require("@zougt/some-loader-utils");
const multipleScopeVars = [
  {
    scopeName: "theme-default",
    path: path.resolve("./src/assets/less/light.vars.less"),
  },
  {
    scopeName: "theme-mauve",
    path: path.resolve("./src/assets/less/dark.vars.less"),
  },
];

module.exports = {

    css: {
    loaderOptions: {
        less: {
            lessOptions: {
                javascriptEnabled: true,
            },
            implementation: getLess({
                getMultipleScopeVars: (lessOptions) => multipleScopeVars,
            }),
        },
    },
    }
 
}
`

依赖的包: 

  `"dependencies": {
    "ant-design-vue": "^1.7.8",
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@zougt/some-loader-utils": "^1.1.4",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^4.1.1",
    "less-loader": "^7.0.0",
    "vue-template-compiler": "^2.6.11"
  }`

编译的时候报错:
![image](https://user-images.githubusercontent.com/5426866/131163613-5bca27de-cd03-4a56-a675-ab2a2f5e3c58.png)

当我把 less-loader 版本升级到 8 的时候 编译报错:
![image](https://user-images.githubusercontent.com/5426866/131164166-94ab6497-f449-414a-8dd2-d5e887660824.png)

**Comment by GitOfZGT** [comment]
首先确认你当前用的less-loader版本， 因为较低版本的less-loader还不支持implementation属性，如果用sass-loader也是同理

**Comment by GitOfZGT** [comment]
升级到less-loader 到8的编译报错，可能跟webpack版本有关或者其他依赖有关，在我的这个包中并没有 this.getOptions的操作

**Comment by GitOfZGT** [comment]
查看less-loader v8+，依赖项表明最低支持webpack5，如果你用的webpack4，使用less-loader@7.3.0即可

**Comment by geekpeng** [comment]
> 查看less-loader v8+，依赖项表明最低支持webpack5，如果你用的webpack4，使用less-loader@7.3.0即可

谢了  是的  我已经试出来  webpack4 less-loader只能用 7.3  less 只能是 3.13.1

感谢了这个插件非常好用 找到的其他的换主题的方法
