### ISSUE TITLE
这个有在 umi 中使用吗？

### ISSUE THREAD

**Issue by nuoer2048** [GitOfZGT/some-loader-utils#5]
想问下 如果想在 umi 的项目中使用，应该怎么配置？

**Comment by GitOfZGT** [comment]
![image](https://user-images.githubusercontent.com/21262000/138907376-455d7357-41fa-42da-871e-8d1122f31e0c.png)
umi用这个配置，根据some-loader-utils 的 getLess 在less-loader的使用
