### ISSUE TITLE
 SassError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by qingtiantongxie** [GitOfZGT/some-loader-utils#7]
我运行项目的时候遇到一个报错，导致项目不能启动：

     SassError: Cannot read property 'length' of undefined

这个demo是依据vue-admin-template 改造的：
    请访问： https://github.com/qingtiantongxie/sass-theme

**Comment by GitOfZGT** [comment]
因为sass-loader v8.x 的传入sass的参数缺少了一个， some-loader-utils v.1.4.0-beta.6  也做了兼容处理，不过使用@zougt/theme-css-extract-webpack-plugin的extract会有一点小副作用，  最好升级到 sass-loader v9.x - v10.x就可以了

**Comment by qingtiantongxie** [comment]
升级sass-loader 到 9.0.3  问题解决了  thx very much
